### ISSUE TITLE
Error: Failed to download resource "attica"

### ISSUE THREAD

**Issue by olr666** [adymo/homebrew-kde#60]
I am unsure how to fix this problem, this is the error I get if I try to install kate. Does anyone know the solution?

I saw a similar problem on here and OP was told to edit the automoc4 ftp address, but there doesn't appear to be an ftp address in automoc4.

$ brew install kate
==> Installing kate from adymo/homebrew-kde
==> Installing dependencies for adymo/kde/kate: attica, strigi, docbook, docbook-xsl, doxygen, qjson, libdbusmenu-qt, kdelibs, oxygen-icons, kde-phonon
==> Installing adymo/kde/kate dependency: attica
==> Downloading ftp://ftp.kde.org/pub/kde/stable/attica/attica-0.4.2.tar.bz2

curl: (6) Could not resolve host: ftp.kde.org
Error: Failed to download resource "attica"
Download failed: ftp://ftp.kde.org/pub/kde/stable/attica/attica-0.4.2.tar.bz2

**Comment by emisca** [comment]
see https://github.com/adymo/homebrew-kde/issues/57

**Comment by olr666** [comment]
"I'm trying to install kate.
Attica failed due to ftp.kde.org down, I changed that url to a mirror and it worked.
Then strigi compilation failed see:

https://gist.github.com/anonymous/821b89fdd76139e4752d

Thanks"

What mirror did you use? I'm assuming you mean I would then change the url in automoc4 at the start of automoc4 - below - to the url of this mirror

  homepage 'https://techbase.kde.org/Development/Tools/Automoc4'
  url 'http://download.kde.org/stable/automoc4/0.9.88/automoc4-0.9.88.tar.bz2'
  sha1 'd864c3dda99d8b5f625b9267acfa1d88ff617e3a'

**Comment by olr666** [comment]
I found the .rb for attica and have tried a number of mirrors in place of the ftp, but still no luck. Errors as below. I'm not sure what's going wrong

"
brew install kate
==> Installing kate from adymo/homebrew-kde
Error: /usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:6: unknown regexp options - ftp
/usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:6: no .<digit> floating literal anymore; put 0 before dot
...e.org/stable/attica/attica-0.4.2.tar.bz2'
...                               ^
/usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:6: syntax error, unexpected tINTEGER, expecting '('
....org/stable/attica/attica-0.4.2.tar.bz2'
...                               ^
/usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:7: syntax error, unexpected tINTEGER, expecting keyword_end
  sha1 '5ae4adcb99db839902b70afd3d1cc7fd471bacd7'
         ^
/usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:9: syntax error, unexpected tIDENTIFIER, expecting keyword_end
  depends_on 'cmake' => :build
                   ^
/usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:10: syntax error, unexpected tIDENTIFIER, expecting keyword_end
  depends_on 'qt' => ["with-d-bus", "with-qt3support"]
                ^
/usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:10: unterminated string meets end of file
/usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:10: syntax error, unexpected end-of-input, expecting keyword_end
Please report this bug:
    https://git.io/brew-troubleshooting
"

I also restored it to the original ftp and ran brew doctor and received this error

"Error: Failed to import: adymo/kde/base_kde_formula
formulae require at least a URL"

**Comment by emisca** [comment]
type brew edit attica

this worked for me:

require 'formula'

class Attica < Formula
  homepage 'http://www.kde.org/'
  url 'ftp://ftp.heanet.ie/mirrors/ftp.kde.org/stable/attica/attica-0.4.2.tar.bz2'
  sha1 '5ae4adcb99db839902b70afd3d1cc7fd471bacd7'

  depends_on 'cmake' => :build
  depends_on 'qt' => ["with-d-bus", "with-qt3support"]

  def install
    system "cmake #{std_cmake_parameters} ."
    system "make install"
  end
end

**Comment by olr666** [comment]
mmm...still getting trouble when I get to strigi

"-- Configuring incomplete, errors occurred!
See also "/tmp/strigi20150606-32237-5k5318/strigi-0.7.8/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/strigi20150606-32237-5k5318/strigi-0.7.8/build/CMakeFiles/CMakeError.log".
"

You appeared to get it working in #57 , did you just ad the recommended code at the end and that's it? Because that configuring error I'm getting is what that code included

**Comment by emisca** [comment]
I got one error first time I've tried. Reissuing same command 'brew install kate' it worked....

**Comment by olr666** [comment]
Maybe I accidentally deleted something in the strigi.rd file when I tried to edit it before...

Can you do me a huge favour and post the contents in your strigi.rb file so I can compare them to mine?

**Comment by emisca** [comment]
https://github.com/adymo/homebrew-kde/blob/master/strigi.rb

On Sat, Jun 6, 2015 at 11:55 AM, olr666 <notifications@github.com> wrote:

> Maybe I accidentally deleted something in the strigi.rd file when I tried
> to edit it before...
>
> Can you do me a huge favour and post the contents in your strigi.rb file
> so I can compare them to mine?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adymo/homebrew-kde/issues/60#issuecomment-109564427>.
>



-- 

*{* name : "Emilio Scalise",
title : "Technical Service Engineer",
phone : "+353892027716",
location : "Dublin, IE",
twitter : ["@MongoDB
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2Fmongodb&sa=D&sntz=1&usg=AFQjCNGEAIAhZyZhF7Z9ORWsRliTuc-2dg>
", "@MongoDBInc
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FMongoDBInc&sa=D&sntz=1&usg=AFQjCNH9Zm1xgTMok-W3GyJEcGcBsz7xnw>
"],
facebook : ["MongoDB
<https://www.google.com/url?q=https%3A%2F%2Fwww.facebook.com%2Fmongodb&sa=D&sntz=1&usg=AFQjCNGPMcaFBzmWsh-MpaWeTH6vMQoDIg>
", "MongoDB, Inc.
<http://www.google.com/url?q=http%3A%2F%2Fwww.facebook.com%2Fmongodbinc&sa=D&sntz=1&usg=AFQjCNEqXl7N-lTJTvsA4RbtY1xEm0I8Zw>
"] *}*

**Comment by olr666** [comment]
Thanks! That got it moving a bit but then another error... something out there hates me, every time one problem is fixed another pops up haha

Have you ever seen this before?


==> Patching
patching file libstreamanalyzer/plugins/endplugins/ffmpegendanalyzer.cpp
/usr/bin/patch: **** malformed patch at line 33: @@ -5,3 +5,4 @@

Error: Failure while executing: /usr/bin/patch -g 0 -f -p1

**Comment by emisca** [comment]
do you have a different patch command instead of the stock OSX one?

**Comment by olr666** [comment]
Sorry for the delayed reply, had exams. I don't believe I have changed the patch command, how would I check if it isn't the stock on?

**Comment by adymo** [comment]
"brew update" should fix attica problem and most strigi compilation problems. @olr666 please open a new issue if strigi problem is not solved for you
